# Generated by Django 2.1.5 on 2019-02-02 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeOfUSER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Возраст пользователя',
                'verbose_name_plural': 'Возроста пользователей',
            },
        ),
        migrations.CreateModel(
            name='CategoryOFUSER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория пользователя',
                'verbose_name_plural': 'Категории пользователей',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image_of_user')),
                ('registration_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileOF.AgeOfUSER')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileOF.CategoryOFUSER')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='RatingOFUSER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Рейтинг пользователя',
                'verbose_name_plural': 'Рейтинг пользователей',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileOF.RatingOFUSER'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
