# Generated by Django 2.1.5 on 2019-02-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datingcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datingcore.CityOFUSER'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'NOT_SELECTED')], default=2),
        ),
    ]
